### ISSUE TITLE
Config for radius

### ISSUE THREAD

**Issue by Shirobachi** [touchportal/harvester#3]
Would be possible to change radius, I did not saw config file and I don't know how to do that :D 

Maybe would you like to add some config?

PS. Thanks for that datapack, it's awesome! <3

**Comment by touchportal** [comment]
Hey thanks! I am working on a config system but the radius is currently hard-coded. An update for this won't come too soon, maybe a month after MC 1.17 comes out.

**Comment by Shirobachi** [comment]
I got it, anyway thank you for this data pack <3
